<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zs</string>
	</array>
	<key>name</key>
	<string>Zen Script - Minetweaker</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>var</string>
			<key>match</key>
			<string>\b(var|val|bool|byte|short|int|long|float|double|string)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>package import</string>
			<key>match</key>
			<string>^\s*(import)\b(?:\s*([^ ;$]+)\s*(;)?)?</string>
			<key>name</key>
			<string>keyword.other.minetweaker</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>inline comments</string>
			<key>match</key>
			<string>\s*((#).*$\n?)</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>block comments</string>
			<key>end</key>
			<string>\*\/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>control keywords</string>
			<key>match</key>
			<string>\b(return|break|case|continue|default|do|while|for|in|switch|if|else)\b</string>
			<key>name</key>
			<string>keyword.control.minetweaker</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constants (true, false, null)</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.minetweaker</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
			<key>name</key>
			<string>constant.numeric.minetweaker</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>assignment operator</string>
			<key>match</key>
			<string>(=|\+=|-=|\/=|%=|\*=|^=|\|=|&amp;=|~=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.minetweaker</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>math operators</string>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.minetweaker</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>arrays</string>
			<key>match</key>
			<string>\b((?:[a-z]\w*\.)*[A-Z]+\w*)(?=\[)</string>
			<key>name</key>
			<string>storage.type.object.array.minetweaker</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ore/liquid dictionary</string>
			<key>match</key>
			<string>(&lt;)\b(?:\s*(ore|liquid))(?:\s*(:)?)(?:(\w|\.|:)*)\b(?:&gt;)?</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>double quote string</string>
			<key>contentName</key>
			<string>string.other</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.minetweaker</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>single quote string</string>
			<key>contentName</key>
			<string>string.other</string>
			<key>end</key>
			<string>\'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.minetweaker</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.minetweaker</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.minetweaker</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.minetweaker</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.minetweaker</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>functions like function</string>
			<key>match</key>
			<string>\b(function)\s?(\()(.*?)(\))</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>built in functions</string>
			<key>match</key>
			<string>(moveResearch|clearPrereqs|addPrereq|removeTab|addBasinRecipe|addAlloy|removeAlloy|addTableRecipe|print|anyDamage|onlyWithTag|transformDamage|withAmount|withTag|withDamage|addShapedMirrored|addShaped|addShapeless|addRecipe|setFuel|removeShapeless|removeShaped|removeMelting|only|marked|matches|applyTransform|weight|updateTag|addMelting|addAll|add|mirror|reuse|transformReplace|onlyDamaged|onlyDamageAtLeast|onlyDamageAtMost|onlyDamageBetween|removeRecipe|remove|transform)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.minetweaker</string>
	<key>uuid</key>
	<string>71a9229f-3e62-4a32-bbb2-6e281f391af8</string>
</dict>
</plist>
